# Generated by Django 3.0.8 on 2020-09-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200926_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
