# Generated by Django 3.0.8 on 2020-10-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200927_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achivements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to='avtar/'),
        ),
    ]
