# Generated by Django 3.0.8 on 2020-10-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201009_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='short_info',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
