# Generated by Django 3.0.8 on 2020-10-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201009_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible_home',
            field=models.BooleanField(default=False),
        ),
    ]
