# Generated by Django 3.0.8 on 2020-08-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0002_auto_20200810_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_excel_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_pdf_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
