# Generated by Django 3.0.8 on 2020-08-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0003_auto_20200810_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_excel_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_pdf_link',
            new_name='youtube_link',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_youtube_link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(blank=True, choices=[('document', 'DOCUMENT'), ('youtubelink', 'YOUTUBELINK'), ('embeddedlink', 'EMBEDDEDLINK'), ('link', 'LINK')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course_section',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='thaatee_lms.CourseSection'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='embedded_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
