# Generated by Django 3.0.8 on 2020-08-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0004_auto_20200810_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('document', 'DOCUMENT'), ('youtubelink', 'YOUTUBELINK'), ('embeddedlink', 'EMBEDDEDLINK'), ('link', 'LINK')], max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course_section',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='thaatee_lms.CourseSection'),
        ),
    ]
