# Generated by Django 3.0.8 on 2020-08-12 17:37

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0006_auto_20200811_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='options',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='thaatee_lms.Quiz'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_title',
            field=models.TextField(),
        ),
    ]
