# Generated by Django 3.0.8 on 2020-08-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0007_auto_20200812_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
