# Generated by Django 3.0.8 on 2020-09-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0008_auto_20200812_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lmscategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
