# Generated by Django 3.0.8 on 2020-09-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0009_auto_20200919_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscategory',
            name='facts',
            field=models.TextField(blank=True),
        ),
    ]
