# Generated by Django 3.0.8 on 2020-09-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0010_lmscategory_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscategory',
            name='origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lmscategory',
            name='category_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lmscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
