# Generated by Django 3.0.8 on 2020-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0011_auto_20200919_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='shot_description',
        ),
        migrations.AddField(
            model_name='courses',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
