# Generated by Django 3.0.8 on 2020-09-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0012_auto_20200920_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
