# Generated by Django 3.0.8 on 2020-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0014_courses_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscategory',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
