# Generated by Django 3.0.8 on 2020-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0015_lmscategory_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
