# Generated by Django 3.0.8 on 2020-10-03 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0016_courses_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyHiglight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('document', 'DOCUMENT'), ('youtubelink', 'YOUTUBELINK'), ('embeddedlink', 'EMBEDDEDLINK'), ('link', 'LINK')], max_length=300)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='files/')),
                ('upload_Video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('embedded_link', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thaatee_lms.Courses')),
            ],
            options={
                'db_table': 'key_highlights',
            },
        ),
    ]
