# Generated by Django 3.0.8 on 2020-10-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_lms', '0018_auto_20201009_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='display_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lmscategory',
            name='display_home',
            field=models.BooleanField(default=False),
        ),
    ]
