# Generated by Django 3.0.7 on 2020-08-03 15:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thaatee_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('viwes_count', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thaatee_blog.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thaatee_blog.SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='thaatee_blog.Blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rate',
            },
        ),
    ]
