# Generated by Django 3.0.8 on 2020-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_blog', '0002_blog_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
