# Generated by Django 3.0.8 on 2020-08-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_blog', '0003_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
