# Generated by Django 3.0.8 on 2020-09-20 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thaatee_blog', '0004_auto_20200809_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('event_image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('event_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('small_description', models.CharField(blank=True, max_length=200, null=True)),
                ('event_location', models.CharField(max_length=1000)),
                ('event_price', models.IntegerField(default=0)),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
