# Generated by Django 3.0.8 on 2020-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_blog', '0006_blog_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
