# Generated by Django 3.0.8 on 2020-10-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_blog', '0007_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
