# Generated by Django 3.0.8 on 2020-08-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.BigIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('discription', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('position', models.IntegerField(default='0')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'home_slider',
            },
        ),
        migrations.CreateModel(
            name='ImgGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'img_gallery',
            },
        ),
        migrations.CreateModel(
            name='OfferSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('position', models.IntegerField(default='0')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Offer_Slide',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.CharField(blank=True, max_length=100)),
                ('seo_keyword', models.CharField(blank=True, max_length=100)),
                ('page_content', models.TextField(blank=True, default='', null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('page_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('client_image', models.ImageField(blank=True, default='', null=True, upload_to='testimonials/')),
                ('client_testimonials', models.TextField(blank=True, default='', null=True)),
                ('home_status', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'testimonials',
            },
        ),
    ]
