# Generated by Django 3.0.8 on 2020-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaatee_frontend', '0002_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
