# Generated by Django 3.0.8 on 2020-10-20 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thaatee_frontend', '0003_homeslide_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.BigIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_instructor',
            },
        ),
    ]
